[build]
builder = "NIXPACKS"

[build.nixpacksConfigPath]
path = "nixpacks.toml"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
PYTHONIOENCODING = "utf-8"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"